# -*- coding: utf-8 -*-
"""movie_main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/133PSHR226ROs4dRVgqLxaQVqq35_amCx

# movie_main
"""

# !pip install deepctr
# !pip install import-ipynb

from deepctr.feature_column import SparseFeat,get_feature_names
from deepctr.models import FLEN, DeepFM
from sklearn.metrics import log_loss, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
import tensorflow as tf
import import_ipynb

# !pip install tensorflow==2.8.0
print(tf.__version__)

from google.colab import drive
drive.mount('/content/drive')
#드라이브 연결

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Colab Notebooks/git_test/dl/dl"

!ls

from movie_define_model import define_model

#define_model이라는 함수에서, df를 들고와 a라는 객체에 저장해주고
# 해당 a를 실행했을 때, csv로 바꿔주는!
# 해당 저장경로는 따로 설정하기
a = define_model()
a.to_csv('/content/drive/MyDrive/Colab Notebooks/git_test/dl/dl/final.csv', index=False)
